# Databricks notebook source
# MAGIC %run "./model/workhorse"

# COMMAND ----------

# TODO TODAY

# REFACTOR LAGGED FEATURES
# RUN REFACTORED VERSION ON SAMPLE DATASET

# EXPLORATION CODE AND NTB
# PIPELINE PROPOSITION
