# Databricks notebook source
# MAGIC %run "./user-model/workhorse"

# COMMAND ----------

#
##
### REES46

split_save_user_model("rees46")


# COMMAND ----------

# TODO TODAY

# REFACTOR LAGGED FEATURES - DONE
# SAMPLE FULL DATASET - DONE
# RUN REFACTORED VERSION ON FULL DATASET

# EXPLORATION
# INDIVIDUAL FEATURE PROPERTIES
# MULTI FEATURE PROTEPRTIES

# MODELING
# WRITE IT ON SMALL DATASET IN SKLEARN

# HYPEROPT

# PIPELINE
# IMPUTATION
# FILTER - NZV, MULTICORR, TARGET CORR
# UNDER/OVER SAMPLING
# SCALING - QUANTILE TRANSFORMER
# FIT

# EVALUATE
# REGRESSION - MAE, MSE
# CLASSIFICATION - ACC, PRE, REC, F1, AUC
# COST-BENEFIT METRICS - H-measure, MP, EMP, R-EMP
