# Databricks notebook source
# MAGIC %run "./customer-model/workhorse"

# COMMAND ----------

 #spark.sql("CREATE SCHEMA IF NOT EXISTS churndb LOCATION \"dbfs:/mnt/churndb\"")

# COMMAND ----------

#
##
### REES46

split_save_customer_model("rees46")


# COMMAND ----------

# TODO

# EXPLORATION
# INDIVIDUAL FEATURE PROPERTIES
# MULTI FEATURE PROTEPRTIES

# MODELING
# WRITE IT ON SMALL DATASET IN SKLEARN

# HYPEROPT

# PIPELINE
# IMPUTATION
# FILTER - NZV, MULTICORR, TARGET CORR
# UNDER/OVER SAMPLING
# SCALING - QUANTILE TRANSFORMER
# FIT

# EVALUATE
# REGRESSION - MAE, MSE
# CLASSIFICATION - ACC, PRE, REC, F1, AUC
# COST-BENEFIT METRICS - H-measure, MP, EMP, R-EMP
